input_dir: work/input
output_dir: work/output
data_dir: work/data
file_selection:
  default_action: exclude
  rules:
    - match: "**/test*.md"
      action: include
    - match: "**/*index.md"
      action: exclude
    - match: "**/*3.md"
      action: exclude
resource_selection:
  default_action: exclude
  rules:
    - match: "**/*.url"
      action: include
    - match: "**/*.jpeg"
      action: include
    - match: "**/*.jpg"
      action: include
    - match: "**/*.pdf"
      action: include
llm:
  translator:
    technical:
      url: http://127.0.0.1:11434
      model: ollama-mock
      timeout_seconds: 5.0
      max_retries: 2
      temperature: 0.0
      max_pre_context_bytes: 2400
      max_post_context_bytes: 2400
      max_input_fragment_bytes: 2400
      max_total_text_bytes: 6000
      system_prompt: |
        You are a professional translator from french to english.
      user_prompt: |
        ===BEGIN PREVIOUS CONTEXT===
        ${pre_context}
        ===END PREVIOUS CONTEXT===

        ===BEGIN SOURCE TEXT===
        ${input_fragment}
        ===END SOURCE TEXT===

        ===BEGIN FOLLOWING CONTEXT===
        ${post_context}
        ===END FOLLOWING CONTEXT===
      translated_document_header: "<!-- Translated automatically ; profile: technical -->"
      translated_document_footer: "<!-- End automatic translation ; profile: technical -->"        