input_dir: work/input
output_dir: work/output
data_dir: work/data
file_selection:
  default_action: exclude
  rules:
    - match: "**/test*.md"
      action: include
    - match: "**/*index.md"
      action: exclude
    - match: "**/*3.md"
      action: exclude
llm:
  translator:
    technical:
      url: http://127.0.0.1:11434
      model: ollama-mock
      timeout_seconds: 5.0
      max_retries: 2
      temperature: 0.0
      system_prompt: |
        You are a professional translator from french to english.
      user_prompt: |
        ===BEGIN SOURCE TEXT===
        ${input_fragment}===END SOURCE TEXT===
      translated_document_header: "<!-- Translated automatically ; profile: technical -->"
      translated_document_footer: "<!-- End automatic translation ; profile: technical -->"        